//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [DisplayName ("Mã sách ")]
        public string MaSach { get; set; }
        [DisplayName("Mã đơn hàng ")]
        public string MaDonHang { get; set; }
        [DisplayName("Số lượng ")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayName("Đơn giá ")]
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
