//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [DisplayName ("Mã khách hàng ")]    
        
        public string MaKH { get; set; }
        [DisplayName("Họ và tên ")]
        public string HoTen { get; set; }
        [DisplayName("Tài khoản ")]
        public string TaiKhoan { get; set; }
        [DisplayName("Mật khẩu ")]
        public string MatKhau { get; set; }
        [DisplayName("Email ")]
        public string Email { get; set; }
        [DisplayName("Địa chỉ ")]
        public string DiaChi { get; set; }
        [DisplayName("Điện thoại ")]
        public string DienThoai { get; set; }
        [DisplayName("Giới tính ")]
        public bool GioiTinh { get; set; }

        [DisplayName("Ngày sinh ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
