//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TacGia()
        {
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public string MaTacGia { get; set; }
        [DisplayName("Mã tác gi?")]
        public string TenTacGia { get; set; }
        [DisplayName("Tên tác gi?")]
        public string DiaChi { get; set; }
        [DisplayName("??a ch?")]
        public string TieuSu { get; set; }
        [DisplayName("Ti?u s?")]
        public string DienThoai { get; set; }
        [DisplayName("?i?n tho?i")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
